# Generated by Django 5.2.14 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(choices=[('info', '普通'), ('warning', '重要'), ('critical', '紧急')], default='warning', max_length=20, verbose_name='级别')),
                ('target_group', models.CharField(choices=[('all', '全部'), ('families', '家属'), ('staff', '员工')], default='families', max_length=20, verbose_name='通知对象')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
