# Generated by Django 5.2.14 on 2026-06-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('visitor_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='访客体温')),
                ('staff_name', models.CharField(max_length=50, verbose_name='接待员工')),
                ('summary', models.TextField(blank=True, verbose_name='探视记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_record', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
