# Generated by Django 5.2.14 on 2026-06-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50, verbose_name='家属姓名')),
                ('family_phone', models.CharField(max_length=30, verbose_name='家属电话')),
                ('relationship', models.CharField(max_length=30, verbose_name='关系')),
                ('visit_time', models.DateTimeField(verbose_name='预约探视时间')),
                ('visitor_count', models.PositiveIntegerField(default=1, verbose_name='访客人数')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='residents.resident')),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
    ]
