# Generated by Django 5.2.14 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('care_level', models.CharField(choices=[('self_care', '自理'), ('assisted', '介助'), ('nursing', '介护')], max_length=20, verbose_name='护理等级')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=30, verbose_name='紧急联系电话')),
                ('medical_notes', models.TextField(blank=True, verbose_name='健康备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['room_number', 'name'],
            },
        ),
    ]
